map ctrl+up   scroll_to prev-file
map cmd+up    scroll_to prev-file
map ctrl+down scroll_to next-file
map cmd+down  scroll_to next-file

map n         scroll_to next-match
map shift+n   scroll_to prev-match
