#!/usr/bin/env bash
windowCount=$(tmux list-windows | wc -l)
currentWindow=$1
direction=$2

if [[ $currentWindow == 0 && $direction == 'left' ]]; then
	for i in $(seq 2 $windowCount); do 
		tmux swap-window -t +1
		tmux next-window
	done
elif [[ $currentWindow == $(($windowCount - 1)) && $direction == 'right' ]]; then
	for i in $(seq 2 $windowCount); do 
		tmux swap-window -t -1
		tmux previous-window
	done
elif [[ $direction == 'left' ]]; then
	tmux swap-window -t -1
	tmux previous-window
elif [[ $direction == 'right' ]]; then
	tmux swap-window -t +1
	tmux next-window
fi
