TIMER_THRESHOLD=1
TIMER_FORMAT='⏲ %d'

ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(backward-kill-word backward-kill-dir)
ZSH_AUTOSUGGEST_STRATEGY=(abbreviations history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=256
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=244"
