theme = "base16_custom"

[editor]
text-width = 120
mouse = false
auto-save.focus-lost = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
auto-signature-help = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[keys.normal]
C-q = ":wqa"

[keys.insert]
A-space = "signature_help"

[keys.select]

[keys.normal.space]
B = "file_picker_in_current_buffer_directory"
