theme = "theme_link"

[editor]
text-width = 120
auto-save.focus-lost = true
popup-border = "all"
color-modes = true
rulers = [80, 120]
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
auto-signature-help = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 2

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
C-q = ":wqa!"

C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"

A-u = "move_line_up"
A-n = "move_char_left"
A-e = "move_line_down"
A-i = "move_char_right"

[keys.insert]
C-space = "completion"
A-space = "signature_help"
C-q = ":wqa"

C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"

[keys.select]

[keys.normal.space]
B = "file_picker_in_current_buffer_directory"
e = "file_explorer_in_current_directory"
f = "file_picker_in_current_directory"
l = ":reload"
r = ":reset-diff-change"
space = "buffer_picker"
x = ":buffer-close"
